#Server
server:
  port: 8080

#DataSourse
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis_like
    username: XXX
    password: XXX

  redis:
    # redis?
    database: 0
    # redis ?????
    host: XXX
    # redis ???
    port: 6379
    # redis ??
    password: XXX
    # ??????????
    timeout: 1000
    jedis:
      pool:
        # ??????????????????
        max-active: 10
        # ?????????????????????
        max-wait: -1
        # ??????????
        max-idle: 10
        # ??????????
        min-idle: 0

#mybatis-plus
logging:
  level:
    com.csu.edu.redisLikeDemo.mapper: trace